# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weathers = pd.read_csv("cities.csv")
weathers = weathers.drop(["Unnamed: 0"], axis = 1)
weathers.head(10)

,City,Country,Latitude,Longitude,Date,Cloudiness,Humidity,Max Temp,Wind Speed
0,lata,PT,40.1629,-8.3327,1.585239e+09,75.0,67.0,59.00,11.41
1,avarua,CK,-21.2078,-159.7750,1.585239e+09,20.0,94.0,73.40,2.24
2,kaitangata,NZ,-46.2817,169.8464,1.585239e+09,100.0,78.0,48.99,1.99
3,rikitea,PF,-23.1203,-134.9692,1.585239e+09,89.0,88.0,75.33,24.49
4,ushuaia,AR,-54.8000,-68.3000,1.585239e+09,40.0,53.0,51.80,16.11
5,terra santa,BR,-2.1042,-56.4869,1.585239e+09,100.0,66.0,86.67,4.25
6,mataura,NZ,-46.1927,168.8643,1.585239e+09,98.0,79.0,48.99,3.18
7,upernavik,GL,72.7868,-56.1549,1.585239e+09,100.0,72.0,-1.89,10.87
8,praia da vitoria,PT,38.7333,-27.0667,1.585239e+09,40.0,58.0,59.00,8.55
9,barrow,US,71.2906,-156.7887,1.585239e+09,1.0,75.0,-18.40,11.41

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Store latitude and longitude in locations
locations = weathers[["Latitude", "Longitude"]]
humidity = weathers["Humidity"].astype(float)
intensity = humidity.max()

In [4]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=intensity, point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
#A max temperature lower than 80 degrees but higher than 70.
#Wind speed less than 10 mph.
#Zero cloudiness.
hotel_df = weathers.loc[(weathers["Cloudiness"] == 0) & (weathers["Max Temp"] > 70) 
                                & (weathers["Max Temp"] < 80) & (weathers["Wind Speed"] < 10)]

hotel_df = hotel_df.reset_index(drop = True)
hotel_df.head()

,City,Country,Latitude,Longitude,Date,Cloudiness,Humidity,Max Temp,Wind Speed
0,tura,IN,25.5198,90.2201,1.585239e+09,0.0,38.0,78.93,3.38
1,saint-pierre,RE,-21.3393,55.4781,1.585239e+09,0.0,74.0,78.80,8.05
2,alice springs,AU,-23.7000,133.8833,1.585239e+09,0.0,46.0,71.60,5.82
3,lebu,CL,-37.6167,-73.6500,1.585239e+09,0.0,50.0,72.63,4.59
4,wanning,CN,18.8003,110.3967,1.585239e+09,0.0,87.0,76.59,8.95

In [6]:
hotel_df["Hotel Name"] = ""

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "types":"lodging",
    "key":g_key,
    "radius":5000
}


for index, row in hotel_df.iterrows():
    params["location"] = f"{row['Latitude']},{row['Longitude']}"
    
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']

    try:
        print(f"First hotel in 5000 meters is {results[0]['name']}.")
        hotel_df.loc[index,"Hotel Name"] = results[0]['name']
     
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 0: tura
First hotel in 5000 meters is Hotel RIKMAN Continental.
------------
Retrieving Results for Index 1: saint-pierre
First hotel in 5000 meters is Lindsey Hôtel.
------------
Retrieving Results for Index 2: alice springs
First hotel in 5000 meters is Desert Palms Alice Springs.
------------
Retrieving Results for Index 3: lebu
First hotel in 5000 meters is Hostal Las Lilas.
------------
Retrieving Results for Index 4: wanning
First hotel in 5000 meters is Paradise Hotel.
------------
Retrieving Results for Index 5: teacapan
First hotel in 5000 meters is Hotel los Mangos.
------------
Retrieving Results for Index 6: geraldton
First hotel in 5000 meters is Broadwater Mariner Resort.
------------
Retrieving Results for Index 7: yenangyaung
First hotel in 5000 meters is Hotel Country.
------------
Retrieving Results for Index 8: saint-philippe
First hotel in 5000 meters is Chambres d'hôte "La Trinité".
------------
Retrieving Results for Index 9: ilhabela
First hotel in 5000 meters is Ilha Flat Hotel.
------------
Retrieving Results for Index 10: san luis
First hotel in 5000 meters is Huarpes Hotel.
------------
Retrieving Results for Index 11: castanos
First hotel in 5000 meters is Monica Amairany.
------------
Retrieving Results for Index 12: pakxan
First hotel in 5000 meters is Kong Kham Pheng Guesthouse.
------------
Retrieving Results for Index 13: bundu
First hotel in 5000 meters is Rajdhani Hotel.
------------
Retrieving Results for Index 14: san rafael
First hotel in 5000 meters is Hotel San Rafael.
------------

In [8]:
hotel_df.head()

,City,Country,Latitude,Longitude,Date,Cloudiness,Humidity,Max Temp,Wind Speed,Hotel Name
0,tura,IN,25.5198,90.2201,1.585239e+09,0.0,38.0,78.93,3.38,Hotel RIKMAN Continental
1,saint-pierre,RE,-21.3393,55.4781,1.585239e+09,0.0,74.0,78.80,8.05,Lindsey Hôtel
2,alice springs,AU,-23.7000,133.8833,1.585239e+09,0.0,46.0,71.60,5.82,Desert Palms Alice Springs
3,lebu,CL,-37.6167,-73.6500,1.585239e+09,0.0,50.0,72.63,4.59,Hostal Las Lilas
4,wanning,CN,18.8003,110.3967,1.585239e+09,0.0,87.0,76.59,8.95,Paradise Hotel

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [10]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))